install:
	pip install --upgrade pip &&\
	pip install -r requirements.txt

format:
	black * .py

lint:
	flake8 --max-line-lengh=88 * .py

test:
	pytest -v

all: install lint test

teste2:
	echo "Hello World"